### ISSUE TITLE
Object.getOwnPropertySymbols

### ISSUE THREAD

**Issue by FredyC** [medikoo/es6-symbol#1]
Are you planning to implemented that ? https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object.getownpropertysymbols.

**Comment by WebReflection** [comment]
@FredyC FYI this alternative brings that method and more compliant Symbol in: https://github.com/WebReflection/get-own-property-symbols

**Comment by medikoo** [comment]
I'll keep it open until some solution will be provided

**Comment by FredyC** [comment]
And there is someone who is actually using this with all Babel floating around? :)

**Comment by medikoo** [comment]
[8 million downloads last month](https://www.npmjs.com/package/es6-symbol) ... and thanks to this package you don't need babel when you need symbols ;-)

**Comment by WebReflection** [comment]
wasn't this a solution?
https://github.com/es-shims/get-own-property-symbols

**Comment by medikoo** [comment]
> wasn't this a solution? https://github.com/es-shims/get-own-property-symbols

I think it doesn't detect symbol objects created by this polyfill but I double check on that
