### ISSUE TITLE
Don't use a keyword `for` as a key

### ISSUE THREAD

**Issue by ytolstyk** [medikoo/es6-symbol#10]
Rails closure compiler fails when it sees line 40:
`for: d(function (key) {`

Changing `for` to something else resolves the issue.

**Comment by medikoo** [comment]
This rule applies to ECMAScript 3, While this polyfill implements ECMAScript 6 functionality on top of ECMAScript 5 (in non-compatible for ECMAScript 3 way).

Closure compiler you refer, was probably configured to lint ECMAScript 3 code, so it should not be applied here.
