### ISSUE TITLE
IE issue when i install es6-symbol.

### ISSUE THREAD

**Issue by jcs12311** [medikoo/es6-symbol#14]
Before i install es6-symbol on my website, i got the error on IE 11:
Unhandled promise rejection ReferenceError: “Symbol” 未定义(undefined).

but after i install e6-symbol, i got another error, what should i do?
![qq 20160328152330](https://cloud.githubusercontent.com/assets/7412060/14132905/2aabe7c8-f67d-11e5-85ce-2a9e4cb2325d.png)

PS: https://github.com/zloirock/core-js/blob/master/client/core.js#L416 maybe because this code?

**Comment by medikoo** [comment]
@jcs12311 I have no idea.. Why do you assume the error comes from es6-symbol?

**Comment by medikoo** [comment]
@jcs12311 I'm going to close as there's not sufficient info for me to do anything with that.  We're also not certain wether it's issue in es6-symbol.

Still feel free to reopen if you have more information about that
