### ISSUE TITLE
Problems with Symbol.toString() in node 0.12

### ISSUE THREAD

**Issue by remojansen** [medikoo/es6-symbol#16]
The following works in the last few node releases:

```js
let test = Symbol("Something");
expect(test.toString()).to.eql("Symbol(Something)"); // true
```
However, In 0.12:

```
let test = Symbol("Something");
expect(test.toString()).to.eql("Symbol(Something)"); // false
```

It seems to be returning an empty object: `{}`.

Example of [failing test](https://github.com/inversify/InversifyJS/blob/master/test/kernel/kernel.test.ts#L419-L424) can be found [here](https://travis-ci.org/inversify/InversifyJS/builds/148653335) and [here](https://ci.appveyor.com/project/remojansen/inversifyjs/build/55).

**Comment by medikoo** [comment]
@remojansen it's how polyfill works. Lastest node doesn't need polyfill, so you get _native_ `Symbol`, while in v0.12 there's no _native_, so you end with polyfill, and it's not really possible to have working polyfill with `toString` matching standard

**Comment by remojansen** [comment]
No problem thanks for the explanation
