### ISSUE TITLE
How to use in project with no build system?

### ISSUE THREAD

**Issue by trusktr** [medikoo/es6-symbol#17]
I have a project that just uses `<script>` tags for everything (gobals).

Is there a version of this polyfill that I can simply include by script tag?

**Comment by medikoo** [comment]
@trusktr see [_Browser_ notes in _Installation_ documentation](https://github.com/medikoo/es6-symbol#browser). You can prepare a ready bundle with any mentioned tools. Technically you need to point `implement` module as main one, to ensure that `Symbol` will be exposed on global
