### ISSUE TITLE
Publish a compiled version on cdnjs

### ISSUE THREAD

**Issue by binarykitchen** [medikoo/es6-symbol#20]
Similar like https://cdnjs.com/libraries/babel-polyfill

Would be great and makes it easier for us to integrate, test and to create a cljsjs package for it.

Thanks

**Comment by medikoo** [comment]
@binarykitchen great thanks for interest. Still I think, that modular organization of this project doesn't fit well the standalone library model. I would even discourage such usage (although I can understand it can be convenient for testing the library in some scenarios)

Anyway, I'm totally ok with it, if you or someone else prepares it in its own capacity.

**Comment by jcward** [comment]
For others who arrive here: the "[other Symbol polyfill](https://github.com/rousan/symbol-es6)" on github has a compiled version you can just pick up and use: https://cdn.jsdelivr.net/npm/symbol-es6/dist/symbol-es6.min.js

**Comment by QuantumInformation** [comment]
thx @jcward perfect
