### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property '@@toStringTag' of [object Object]

### ISSUE THREAD

**Issue by amangeot** [medikoo/es6-symbol#24]
Hello,
I have an issue with, I believe, the way Symbols are polyfilled. I receive this error when Facebook's regenerator starts polyfilling:
`Uncaught TypeError: Cannot assign to read only property '@@toStringTag' of [object Object]`

Here is a similar issue with another `polyfill-service`:
https://github.com/Financial-Times/polyfill-service/pull/1295

Here's how I use the polyfill:
```
if (typeof Symbol === 'undefined') {
  require('es6-symbol/implement')
}
```

Is it possible to set Symbol.toStringTag to be writable as they do here ?
https://github.com/Financial-Times/polyfill-service/pull/1295/commits/b31d2347c5b3286f33c78e6d0cfef1682c57ef10

**Comment by medikoo** [comment]
@amangeot thanks for report. Still it follows the behavior of native symbol: http://www.ecma-international.org/ecma-262/6.0/#sec-symbol.prototype-@@tostringtag

e.g. run this fiddle in Chrome with console open: https://jsfiddle.net/medikoo/5g66e20r/
It shows exactly same exception when tried on native symbol (no polyfill involved)

If Facebook's regenator crashes on that, it's bug on their side not in this polyfill. Please report it to them

I'm closing it, but if you still have some questions or want to add a comment do not hesitate. Let's continue the discussion.
