### ISSUE TITLE
Symbol.iterator

### ISSUE THREAD

**Issue by sm2017** [medikoo/es6-symbol#25]
First see https://github.com/hiddentao/squel/issues/337

In https://github.com/hiddentao/squel/blob/master/dist/squel.js#L127 we have `handlers[Symbol.iterator]()` that is similar to example `possiblyIterable[Symbol.iterator]();` , Why `handlers[Symbol.iterator]` is `undefined`?

**Comment by medikoo** [comment]
@sm2017 this polyfill just ensures that `Symbol` constructor and predefined symbols  are at your service (in non ES2015+ envs), but does not ensure that all other native types have e.g. `Symbol.iterator` methods implemented

For that you need to load other polyfills, e.g. if you need `Array.prototype[Symbol.iterator]`, you may first need to load e.g. [`es5-ext/array/#/@@iterator/implement`](https://github.com/medikoo/es5-ext#arriterator-es5-extarrayiterator) upfront etc.

I'm going to close this, but if let's keep discussion open if needed
