### ISSUE TITLE
"Object.defineProperty: argument is not an Object" on IE 11

### ISSUE THREAD

**Issue by iwazaru** [medikoo/es6-symbol#26]
[I'm facing an issue with webpack-serve](https://github.com/webpack-contrib/webpack-serve/issues/164) that i've narrowed down to es6-symbol. It may also be a problem with es5-ext so please excuse me if I'm not posting in the right place.

When compiling my project using webpack-serve, it works in Chrome but I'm getting an error in IE 11 / Win 8.1:

> SCRIPT5007: Object.defineProperty: argument is not an Object
> File: implement.js, Line: 4, Column: 2
> //# sourceURL=webpack://log/./node_modules/es6-symbol/implement.js?

I was able to reproduce this in Chrome when forcing `is-implemented.js` to return `false`:

> implement.js:4 Uncaught TypeError: Object.defineProperty called on non-object
>    at Function.defineProperty (<anonymous>)
>    at Object../node_modules/es6-symbol/implement.js (implement.js:4)
>    at __webpack_require__ (bootstrap:716)
>    at fn (bootstrap:98)
>    at Object../src/index.js (index.js:3)
>    at __webpack_require__ (bootstrap:716)
>    at fn (bootstrap:98)
>    at Object.1 (bundle.js:13535)
>    at __webpack_require__ (bootstrap:716)
>    at bootstrap:783

Also, adding this to `implements.js` returns `undefined`:

    console.log(require('es5-ext/global'));

Here's a repo where I replaced all my code with an example from the webpack doc and left only webpack configuration, and where I was still able to reproduce the error after `npm start` and viewing site with IE 11:
https://github.com/iwazaru/webpack-serve-bug

I'm not sure where to go from here, please tell me if you need any additional information.

**Comment by medikoo** [comment]
@iwazaru it looks that bundler you use (or your configuration) forces `strict` mode on CJS modules, and that's obviously breaking.

CJS modules by default work in sloppy mode. We need `'use strict'` pragma to switch it to strict mode, and `es5-ext/global` takes advantage of that.

Try to run `console.log(require('es5-ext/global'))` in Node.js environment, and you'll get as expected a global object. Still if you hack it so it's loaded in strict mode on that, you'll get `undefined`.

I'm closing it, but feel free to continue discussion.

**Comment by iwazaru** [comment]
Thanks for your kind and quick reply, as it helped resolve this issue.

Turns out that `babel` was the culprit, as the `env` preset activates strict mode for every module by default. Changing my babel config from:

    { "presets": [ "env" ] }

to

     { "presets": [ [ "env", { "modules": false } ] ] }

fixed the error.
