### ISSUE TITLE
Error: Properties can only be defined on Objects.

### ISSUE THREAD

**Issue by iffy** [medikoo/es6-symbol#27]
I'm trying to use Symbols on a ReactNative project for Android.  I'm getting this error:

```
Properties can only be defined on Objects.
<unknown>
polyfill.js:36:18
...
```

Here's the code I'm trying to run:

```typescript
  var MYSYMBOL = Symbol.for("matt.testing");
  var singleton;
  if (global[MYSYMBOL] === undefined) {
      // First time
      singleton = global[MYSYMBOL] = 'MY SINGLETON'
  }
  else {
      // Subsequent times
      singleton = global[MYSYMBOL];
  }
  console.log('singleton', singleton)
```

1. I don't know if the bug is with `es6-symbol` or not -- I'm completely new to ReactNative
2. Looking at my code, I'm wondering now why I'm using a Symbol in the first place (instead of just using that `"matt.testing"` string as my key) -- so I may avoid the problem by not using Symbols, but thought I'd report this bug (if it is a bug here).

**Comment by medikoo** [comment]
There is no bug in `es6-symbol`, e.g. below code run perfectly in bare Node.js both v0.12 (one that oesn't implement `Symbol` natively) and Node.js v10 (implements `Symbol`)

```javascript
'var Symbol = require('es6-symbol/polyfill');

var MYSYMBOL = Symbol.for("matt.testing");
var singleton;
if (global[MYSYMBOL] === undefined) {
		// First time
		singleton = global[MYSYMBOL] = 'MY SINGLETON'
}
else {
		// Subsequent times
		singleton = global[MYSYMBOL];
}
console.log('singleton', singleton)
```
