### ISSUE TITLE
Polyfill Symbol description

### ISSUE THREAD

**Issue by jimmywarting** [medikoo/es6-symbol#28]
https://tc39.github.io/proposal-Symbol-description/
```js
Object.defineProperty(Symbol.prototype, 'description', {
  get() {
    return this.toString().slice(7, -1)
  }
})
```

**Comment by medikoo** [comment]
Thanks, for suggestion. Good idea to have it, especially that it's likely to be implemented by engines soon.

I'm open for PR's

**Comment by jimmywarting** [comment]
Don't consider this package as necessary now.
