### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by moritztim** [medikoo/es6-symbol#34]
```
error: Uncaught SyntaxError: Identifier '__2$' has already been declared
    at <anonymous> (https://esm.sh/v120/es6-symbol@3.1.3/deno/es6-symbol.mjs:2:168)
```

Deno CLI:
```ts
import * as _ from "https://esm.sh/v120/es6-symbol/deno/es6-symbol.mjs"
```
> Uncaught SyntaxError: Identifier '__2$' has already been declared
>    at async <anonymous>:2:11

Deno File:
```ts
import * as test from "https://esm.sh/v120/es6-symbol/deno/es6-symbol.mjs"
test;
```
> error: Uncaught SyntaxError: Identifier '__2$' has already been declared
>    at <anonymous> (https://esm.sh/v120/es6-symbol@3.1.3/deno/es6-symbol.mjs:2:168)

**Comment by medikoo** [comment]
@moritz-t-w Please report to entity that publishes `es6-symbol.mjs` at `esm.sh` (I'm not aware who's doing that and where that should be reported).

Otherwise there's no issue in this package
